modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="gemcakes"
version="1.7"
displayName="Gem Cakes"
authors="Visnaa"
description='''
This mod adds cakes made from gems.
'''

[[dependencies.gemcakes]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.gemcakes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.gemcakes]]
    modId="morejewels"
    mandatory=true
    versionRange="[2.9,)"
    ordering="NONE"
    side="BOTH"